const $ = (sel, root=document) => root.querySelector(sel);
const $$ = (sel, root=document) => [...root.querySelectorAll(sel)];

const FALLBACK_EVENTS = [
  { id:'preview-ica', title:'ICA Free Admission', venue:'Institute of Contemporary Art', neighborhood:'Seaport', start:null, time:'All day', price:'FREE', category:'Museums', icon:'◫', tone:'blue', x:73, y:43, source:'Preview', preview:true },
  { id:'preview-sowa', title:'SoWa Open Market', venue:'SoWa Power Station', neighborhood:'South End', start:null, time:'10:00 AM – 4:00 PM', price:'FREE', category:'Markets', icon:'✦', tone:'green', x:52, y:63, source:'Preview', preview:true },
  { id:'preview-redsox', title:'Red Sox at Fenway', venue:'Fenway Park', neighborhood:'Fenway', start:null, time:'Evening', price:'$55+', category:'Sports', icon:'◆', tone:'red', x:37, y:54, source:'Preview', preview:true },
  { id:'preview-bts', title:'Live Music at Roadrunner', venue:'Roadrunner', neighborhood:'Brighton', start:null, time:'8:00 PM', price:'$28', category:'Live Music', icon:'♫', tone:'purple', x:25, y:39, source:'Preview', preview:true },
  { id:'preview-mfa', title:'Museum After Dark', venue:'Museum of Fine Arts', neighborhood:'Fenway', start:null, time:'6:00 PM', price:'$20', category:'Museums', icon:'◇', tone:'blue', x:42, y:59, source:'Preview', preview:true },
  { id:'preview-comedy', title:'Stand Up Showcase', venue:'Laugh Boston', neighborhood:'Seaport', start:null, time:'7:30 PM', price:'$25', category:'Comedy', icon:'☻', tone:'purple', x:69, y:55, source:'Preview', preview:true },
  { id:'preview-movie', title:'Late Screening at Brattle', venue:'Brattle Theatre', neighborhood:'Cambridge', start:null, time:'9:30 PM', price:'$9', category:'Movies', icon:'▶', tone:'blue', x:38, y:25, source:'Preview', preview:true },
  { id:'preview-jazz', title:'Berklee Summer Jazz', venue:'Berklee Performance Center', neighborhood:'Back Bay', start:null, time:'8:00 PM', price:'$18', category:'Live Music', icon:'♪', tone:'purple', x:44, y:49, source:'Preview', preview:true },
  { id:'preview-market', title:'Night Market', venue:'Harvard Square', neighborhood:'Cambridge', start:null, time:'6:00 PM', price:'FREE', category:'Markets', icon:'✺', tone:'green', x:32, y:20, source:'Preview', preview:true },
  { id:'preview-weird', title:'After-Hours Observatory', venue:'Boston University', neighborhood:'Fenway / Kenmore', start:null, time:'9:00 PM', price:'FREE', category:'Weird', icon:'✧', tone:'orange', x:36, y:43, source:'Preview', preview:true },
  { id:'preview-arts', title:'Fort Point Art Walk', venue:'Fort Point', neighborhood:'Fort Point', start:null, time:'5:00 PM – 9:00 PM', price:'FREE', category:'Art', icon:'✦', tone:'purple', x:65, y:58, source:'Preview', preview:true },
  { id:'preview-food', title:'North End Summer Stroll', venue:'Hanover Street', neighborhood:'North End', start:null, time:'6:30 PM', price:'FREE', category:'Food', icon:'◉', tone:'orange', x:59, y:36, source:'Preview', preview:true },
];

const CATEGORIES = ['All','Live Music','Sports','Comedy','Movies','Museums','Markets','Art','Food','Free','Weird'];
const WHEN_FILTERS = ['Tonight','Tomorrow','This weekend','7 days'];
const PRICE_FILTERS = ['Any price','Free','Under $30'];
const BOUNDS = { minLat:42.29, maxLat:42.405, minLon:-71.19, maxLon:-70.96 };

function loadSavedMap(){
  const full = JSON.parse(localStorage.getItem('citylab.savedEvents') || '[]');
  const map = new Map(full.filter(Boolean).map(e=>[e.id,e]));
  const legacy = JSON.parse(localStorage.getItem('citylab.saved') || '[]');
  legacy.forEach(id=>{ const e=FALLBACK_EVENTS.find(x=>x.id===id || x.id===`preview-${id}`); if(e) map.set(e.id,e); });
  return map;
}

const state = {
  tab:'now',
  mbta:{ loading:true, alerts:[], arrivals:[], error:null, arrivalsError:null, arrivalsMode:'Boston hubs' },
  bikes:{ loading:true, total:null, stations:[], error:null },
  events:{ loading:false, items:[...FALLBACK_EVENTS], source:'Preview', error:null, lastUpdated:null },
  city311:{ loading:true, today:null, error:null, resource:null },
  saved:loadSavedMap(),
  category:'All', when:'Tonight', price:'Any price', query:'',
  layers:{ events:true, transit:true, bikes:true, traffic:true },
  cityTime:new Date(), activeEvent:null,
  ticketmasterKey:localStorage.getItem('citylab.ticketmasterKey') || '',
};

function esc(str=''){ return String(str).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m])); }
function nowText(){ return new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(state.cityTime); }
function timeOnly(){ return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(state.cityTime); }
function showToast(text){ const el=$('#toast'); if(!el)return; el.textContent=text; el.classList.add('show'); clearTimeout(showToast.t); showToast.t=setTimeout(()=>el.classList.remove('show'),1700); }
function sourceBadge(e){ return e.source==='Ticketmaster'?'<span class="source-mini live">LIVE</span>':e.source==='Boston.gov'?'<span class="source-mini civic">CITY</span>':'<span class="source-mini preview">PREVIEW</span>'; }
function savePersist(){ localStorage.setItem('citylab.savedEvents',JSON.stringify([...state.saved.values()])); }
function saveEvent(id){ const e=findEvent(id); if(!e)return; if(state.saved.has(id)) state.saved.delete(id); else state.saved.set(id,e); savePersist(); render(); showToast(state.saved.has(id)?'Saved':'Removed'); }
function findEvent(id){ return state.events.items.find(e=>e.id===id) || state.saved.get(id) || FALLBACK_EVENTS.find(e=>e.id===id); }
function priceNumber(price=''){ const m=String(price).match(/\d+(?:\.\d+)?/); return m?Number(m[0]):null; }
function priceTone(price){ if(price==='FREE')return 'green'; const n=priceNumber(price); if(n!=null&&n>=50)return 'red'; return 'blue'; }
function thumbGradient(t){ const g={green:'linear-gradient(145deg,#18352c,#10221e)',blue:'linear-gradient(145deg,#18334e,#101f31)',red:'linear-gradient(145deg,#482027,#28141b)',purple:'linear-gradient(145deg,#34224c,#1e1730)',orange:'linear-gradient(145deg,#49331b,#282014)'}; return g[t]||g.blue; }
function eventThumb(e){ const bg=e.image?`linear-gradient(180deg,transparent 40%,rgba(0,0,0,.55)),url('${esc(e.image)}') center/cover`:thumbGradient(e.tone); return `<div class="event-thumb" style="background:${bg}"><span>${e.image?'':esc(e.icon||'✦')}</span></div>`; }
function eventRow(e,save=false){ return `<div class="${save?'discover-card':'event-row'}" data-open-event="${esc(e.id)}">
  ${eventThumb(e)}
  <div class="event-main"><div class="event-title">${esc(e.title)}</div><div class="event-meta">${esc(e.venue||'Boston')} · ${esc(e.neighborhood||'Boston')}</div><div class="event-time">${esc(e.time||formatEventTime(e.start))} ${sourceBadge(e)}</div></div>
  ${save?`<button class="save-btn ${state.saved.has(e.id)?'saved':''}" data-save="${esc(e.id)}" aria-label="Save ${esc(e.title)}">${state.saved.has(e.id)?'♥':'♡'}</button>`:`<span class="pill ${priceTone(e.price||'')}">${esc(e.price||'Details')}</span>`}
</div>`; }

function formatEventTime(iso){ if(!iso)return 'Time varies'; const d=new Date(iso); if(Number.isNaN(d.getTime()))return 'Time varies'; return new Intl.DateTimeFormat('en-US',{weekday:'short',hour:'numeric',minute:'2-digit'}).format(d); }
function eventDateLabel(e){ if(!e.start)return 'Preview schedule'; const d=new Date(e.start); return new Intl.DateTimeFormat('en-US',{weekday:'long',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(d); }
function categoryTone(category=''){ if(/music/i.test(category))return ['purple','♫']; if(/sport/i.test(category))return ['red','◆']; if(/comedy/i.test(category))return ['purple','☻']; if(/film|movie/i.test(category))return ['blue','▶']; if(/museum|art|theatre|theater/i.test(category))return ['blue','◇']; if(/food/i.test(category))return ['orange','◉']; return ['green','✦']; }
function normalizeCategory(segment='',genre='',sub=''){ const s=`${segment} ${genre} ${sub}`.toLowerCase(); if(s.includes('music'))return 'Live Music'; if(s.includes('sport'))return 'Sports'; if(s.includes('comedy'))return 'Comedy'; if(s.includes('film'))return 'Movies'; if(s.includes('museum'))return 'Museums'; if(s.includes('theatre')||s.includes('theater')||s.includes('arts'))return 'Art'; if(s.includes('food'))return 'Food'; return 'Events'; }
function posFromLatLon(lat,lon){ const x=(lon-BOUNDS.minLon)/(BOUNDS.maxLon-BOUNDS.minLon)*100; const y=(BOUNDS.maxLat-lat)/(BOUNDS.maxLat-BOUNDS.minLat)*100; return {x:Math.max(3,Math.min(97,x)),y:Math.max(6,Math.min(88,y))}; }

function dateBounds(label){ const now=new Date(); const start=new Date(now); let end=new Date(now);
  if(label==='Tonight'){ start.setHours(17,0,0,0); if(now>start) start.setTime(now.getTime()); end=new Date(start); end.setHours(29,0,0,0); }
  else if(label==='Tomorrow'){ start.setDate(start.getDate()+1); start.setHours(0,0,0,0); end=new Date(start); end.setDate(end.getDate()+1); }
  else if(label==='This weekend'){ const day=start.getDay(); const toFri=(5-day+7)%7; start.setDate(start.getDate()+toFri); start.setHours(17,0,0,0); end=new Date(start); end.setDate(end.getDate()+3); end.setHours(2,0,0,0); }
  else { start.setTime(now.getTime()); end=new Date(now); end.setDate(end.getDate()+7); }
  return {start,end};
}
function filteredEvents(){ const {start,end}=dateBounds(state.when); const q=state.query.trim().toLowerCase(); return state.events.items.filter(e=>{
  if(state.category!=='All' && (state.category==='Free' ? e.price!=='FREE' : e.category!==state.category)) return false;
  if(state.price==='Free' && e.price!=='FREE')return false;
  if(state.price==='Under $30'){ const n=priceNumber(e.price); if(e.price!=='FREE' && !(n!=null&&n<30))return false; }
  if(q && !`${e.title} ${e.venue} ${e.neighborhood} ${e.category}`.toLowerCase().includes(q))return false;
  if(e.preview || !e.start)return true;
  const d=new Date(e.start); return d>=start&&d<=end;
 }).sort((a,b)=>(a.preview?1:0)-(b.preview?1:0) || ((new Date(a.start||8640000000000000))-(new Date(b.start||8640000000000000)))); }

function lineSummary(line){
  const routeMap={Green:['Green-B','Green-C','Green-D','Green-E'],Orange:['Orange'],Red:['Red'],Blue:['Blue']};
  const alerts=state.mbta.alerts.filter(a=>(a.attributes?.active_period||[]).some(p=>!p.end||new Date(p.end)>new Date()) && (a.relationships?.route?.data?.id?routeMap[line].includes(a.relationships.route.data.id):true));
  const severe=alerts.filter(a=>['SUSPENSION','DELAY','SHUTTLE'].includes(a.attributes?.effect));
  if(severe.length)return {text:severe.length>1?`${severe.length} alerts`:'Delay',cls:'status-warn'};
  return {text:'Normal service',cls:'status-ok'};
}
function cityPulseScore(){ const h=state.cityTime.getHours(); const timeScore=h>=17&&h<=23?20:h>=11?12:6; const bike=Math.min(25,Math.round((state.bikes.total||1300)/100)); const alertPenalty=Math.min(12,state.mbta.alerts.length*2); const eventBoost=Math.min(8,Math.round(state.events.items.filter(e=>!e.preview).length/8)); return Math.max(42,Math.min(94,55+timeScore+bike+eventBoost-alertPenalty)); }
function cityPulseLabel(){ const s=cityPulseScore(); return s>82?'Very active':s>68?'Active':s>55?'Steady':'Quiet'; }

function arrivalsHtml(){ if(state.mbta.arrivalsError)return `<div class="mini-empty">Arrival feed unavailable</div>`; if(!state.mbta.arrivals.length)return `<div class="mini-empty">Loading upcoming trains…</div>`; return state.mbta.arrivals.slice(0,5).map(a=>`<div class="arrival-row"><span class="route-dot ${a.routeClass}">${esc(a.badge)}</span><div class="arrival-main"><b>${esc(a.routeName)}</b><small>${esc(a.stopName)}${a.direction?' · '+esc(a.direction):''}</small></div><strong>${esc(a.when)}</strong></div>`).join(''); }

function renderNow(){
  const green=lineSummary('Green'),orange=lineSummary('Orange'); const totalAlerts=state.mbta.loading?'—':state.mbta.alerts.length; const bikeTotal=state.bikes.loading?'—':(state.bikes.total?.toLocaleString()||'—'); const liveEvents=state.events.items.filter(e=>!e.preview).length; const eventCount=liveEvents||state.events.items.length;
  return `<header class="header"><div><h1>BOSTON</h1><div class="subhead">${nowText()}</div></div><div class="header-actions"><button class="icon-btn" data-refresh title="Refresh live data">↻</button><button class="icon-btn" data-tab-jump="saved" title="Saved">♡</button></div></header>
  <div class="section"><div class="section-head"><div class="section-title">⌁ City Pulse</div><span class="live-label"><span class="live-dot"></span>Live</span></div><div class="card pulse-card"><div class="pulse-top"><span class="eyebrow">Boston right now</span><strong style="color:var(--green)">${cityPulseLabel()}</strong></div><div class="pulse-wave"><svg viewBox="0 0 500 60" preserveAspectRatio="none"><path d="M0 38 L28 37 L42 34 L55 38 L65 38 L74 11 L84 51 L98 29 L110 38 L151 38 L167 35 L179 40 L195 36 L218 38 L237 18 L248 48 L259 32 L273 38 L320 38 L337 35 L352 41 L366 37 L382 38 L397 21 L409 47 L421 31 L435 38 L500 38" fill="none" stroke="#78db78" stroke-width="2"/><path d="M0 38 H500" stroke="rgba(120,219,120,.14)"/></svg></div><div class="pulse-status"><div><strong>${cityPulseScore()}</strong><div class="pulse-index">City activity index</div></div><div class="pulse-index">Transit · events · bikes · time</div></div></div></div>
  <div class="section"><div class="section-head"><div class="section-title">Transit</div><button class="text-btn" data-nearby-transit>Use my location</button></div><div class="card transit-grid"><div class="transit-cell"><div class="route-row"><span class="route-dot route-green">T</span><div><h3>Green Line</h3><div class="metric-caption ${green.cls}">${green.text}</div></div></div></div><div class="transit-cell"><div class="route-row"><span class="route-dot route-orange">T</span><div><h3>Orange Line</h3><div class="metric-caption ${orange.cls}">${orange.text}</div></div></div></div><div class="transit-cell" style="text-align:center"><b style="font-size:24px;color:${Number(totalAlerts)>0?'var(--red)':'var(--green)'}">${totalAlerts}</b><div class="metric-caption">active alerts</div></div></div></div>
  <div class="section compact-top"><div class="section-head"><div><div class="section-title">Upcoming trains</div><div class="microcopy">${esc(state.mbta.arrivalsMode)}</div></div><button class="text-btn" data-refresh-arrivals>Refresh</button></div><div class="card arrivals-card">${arrivalsHtml()}</div></div>
  <div class="section"><div class="section-head"><div class="section-title">Today</div><button class="text-btn" data-tab-jump="discover">View all</button></div><div class="card today-grid"><div class="big-stat"><b>${eventCount}</b><span>${liveEvents?'live events':'preview things'}</span></div><div class="big-stat green"><b>${state.events.items.filter(e=>e.price==='FREE').length}</b><span>free</span></div><div class="big-stat blue"><b>${state.events.items.filter(e=>{const n=priceNumber(e.price);return e.price==='FREE'||(n!=null&&n<30)}).length}</b><span>under $30</span></div></div></div>
  <div class="section"><div class="section-head"><div><div class="section-title">Coming up near you</div><div class="microcopy">${state.events.source==='Ticketmaster'?'Live event feed':'Preview until event sync is connected'}</div></div><button class="text-btn" data-tab-jump="discover">View all</button></div><div class="card event-list">${filteredEvents().slice(0,4).map(e=>eventRow(e)).join('')||'<div class="empty">No matching events right now.</div>'}</div></div>
  <div class="section"><div class="section-head"><div class="section-title">The city right now</div><button class="text-btn" data-tab-jump="live">Open map</button></div><div class="card city-stats"><div class="city-stat"><div class="ico" style="color:var(--orange)">☏</div><b>${state.city311.today==null?'—':state.city311.today.toLocaleString()}</b><small>311 requests<br>today</small></div><div class="city-stat"><div class="ico" style="color:var(--green)">♧</div><b>${bikeTotal}</b><small>Bluebikes<br>available</small></div><div class="city-stat"><div class="ico" style="color:var(--yellow)">☆</div><b>${eventCount}</b><small>${liveEvents?'live':'preview'}<br>events</small></div><div class="city-stat"><div class="ico" style="color:var(--purple)">⌁</div><b>${cityPulseScore()}</b><small>city<br>pulse</small></div></div></div>`;
}

function renderDiscover(){ const filtered=filteredEvents(); return `<header class="header"><div><h1 style="font-size:31px">DISCOVER</h1><div class="subhead">Find what moves you.</div></div><button class="icon-btn" data-event-source title="Event sources">⌁</button></header>
  <div class="search-box"><span>⌕</span><input id="eventSearch" value="${esc(state.query)}" placeholder="Search events, venues, neighborhoods" autocomplete="off"></div>
  <div class="chips">${CATEGORIES.map(c=>`<button class="chip ${c===state.category?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')}</div>
  <div class="filter-row"><select data-when>${WHEN_FILTERS.map(v=>`<option ${v===state.when?'selected':''}>${v}</option>`).join('')}</select><select data-price>${PRICE_FILTERS.map(v=>`<option ${v===state.price?'selected':''}>${v}</option>`).join('')}</select><span class="source-chip ${state.events.source==='Ticketmaster'?'live':''}">${state.events.loading?'Syncing…':state.events.source}</span></div>
  <div class="section"><div class="section-head"><div><div class="section-title">${esc(state.when)} in Boston</div><div class="microcopy">${state.events.error?esc(state.events.error):state.events.source==='Ticketmaster'?'Live listings · tap any event for details':'Connect Ticketmaster in More for live ticketed events'}</div></div><span class="pill">${filtered.length} results</span></div><div class="card">${filtered.map(e=>eventRow(e,true)).join('')||'<div class="empty"><div class="big">⌕</div><b>No matches</b><p style="margin-top:6px">Try a broader category, date, or price.</p></div>'}</div></div>
  <div class="section"><div class="section-head"><div class="section-title">Trending neighborhoods</div></div><div class="chips"><button class="pill orange" data-search-preset="Fenway">Fenway · high energy</button><button class="pill purple" data-search-preset="Cambridge">Cambridge · creative</button><button class="pill blue" data-search-preset="Seaport">Seaport · waterfront</button><button class="pill green" data-search-preset="Allston">Allston · live music</button><button class="pill" data-search-preset="Back Bay">Back Bay · classic</button></div></div>`; }

function cityMapSvg(){ return `<svg viewBox="0 0 500 760" preserveAspectRatio="none" aria-hidden="true"><defs><filter id="glow"><feGaussianBlur stdDeviation="2.4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path d="M0 170 C80 150 120 200 195 184 C260 170 292 134 344 156 C392 175 420 229 500 224" fill="none" stroke="#0b3248" stroke-width="22" opacity=".6"/><path d="M275 0 C272 90 294 137 325 184 C362 240 372 303 363 371 C354 450 399 501 500 535" fill="none" stroke="#0c2d40" stroke-width="18" opacity=".5"/><g stroke="#1d2b38" stroke-width="1" opacity=".72">${Array.from({length:14},(_,i)=>`<path d="M${-40+i*42} 0 L${90+i*34} 760"/>`).join('')}${Array.from({length:14},(_,i)=>`<path d="M0 ${40+i*52} L500 ${10+i*48}"/>`).join('')}</g><g fill="none" stroke-width="3" filter="url(#glow)"><path d="M45 390 C140 380 192 374 256 354 C330 332 397 320 472 308" stroke="#4db25a"/><path d="M130 610 C178 541 205 480 251 423 C292 370 350 320 455 240" stroke="#ea8c36"/><path d="M230 710 C245 605 259 517 276 445 C290 376 302 300 312 190" stroke="#cf4454"/><path d="M0 250 C87 270 153 302 224 337 C294 372 381 404 500 426" stroke="#397dd1"/></g><g fill="#dbe8ee" opacity=".42">${Array.from({length:45},(_,i)=>`<circle cx="${(i*83)%500}" cy="${60+((i*131)%610)}" r="1.4"/>`).join('')}</g></svg>`; }
function mapMarkers(){ const ev=state.events.items.filter(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)).slice(0,20).map(e=>`<button class="map-marker marker-event ${state.layers.events?'':'hidden'}" style="left:${e.x}%;top:${e.y}%" title="${esc(e.title)}" data-open-event="${esc(e.id)}">${esc(e.icon||'♫')}</button>`).join('');
  const transit=[{x:48,y:43},{x:54,y:48},{x:41,y:57},{x:58,y:38},{x:63,y:31},{x:35,y:34}].map(p=>`<div class="map-marker marker-transit ${state.layers.transit?'':'hidden'}" style="left:${p.x}%;top:${p.y}%">T</div>`).join('');
  const traffic=[{x:57,y:49},{x:46,y:61},{x:67,y:56},{x:32,y:49}].map(p=>`<div class="map-marker marker-traffic ${state.layers.traffic?'':'hidden'}" style="left:${p.x}%;top:${p.y}%">⌁</div>`).join('');
  const bikes=(state.bikes.stations.length?state.bikes.stations.slice(0,22):[{lat:42.352,lon:-71.055},{lat:42.360,lon:-71.093},{lat:42.346,lon:-71.081},{lat:42.373,lon:-71.120},{lat:42.338,lon:-71.034},{lat:42.365,lon:-71.060}]).map(s=>{const p=posFromLatLon(Number(s.lat),Number(s.lon));return `<div class="map-marker marker-bike ${state.layers.bikes?'':'hidden'}" style="left:${p.x}%;top:${p.y}%" title="${esc(s.name||'Bluebikes station')}">♧</div>`}).join(''); return ev+transit+traffic+bikes; }
function renderLive(){ const liveEvents=state.events.items.filter(e=>!e.preview).length; return `<header class="header"><div><h1 style="font-size:30px">LIVE CITY</h1><div class="subhead">Boston in real time.</div></div><div class="header-actions"><button class="icon-btn" data-location>⌖</button><button class="icon-btn" data-refresh>↻</button></div></header><div class="map-shell"><div class="map-art">${cityMapSvg()}</div><div class="map-filters">${[['events','● Events'],['transit','T Transit'],['bikes','♧ Bikes'],['traffic','⌁ Traffic']].map(([k,l])=>`<button class="map-filter ${state.layers[k]?'active':''}" data-layer="${k}">${l}</button>`).join('')}</div><span class="map-label" style="left:15%;top:21%">Cambridge</span><span class="map-label" style="left:66%;top:19%">Charlestown</span><span class="map-label" style="left:78%;top:30%">East Boston</span><span class="map-label" style="left:17%;top:53%">Back Bay</span><span class="map-label" style="left:47%;top:64%">South End</span><span class="map-label" style="left:70%;top:68%">South Boston</span><span class="map-label" style="left:18%;top:76%">Roxbury</span><span class="map-label" style="left:58%;top:82%">Dorchester</span><span class="map-center-label">BOSTON</span>${mapMarkers()}<div class="map-bottom"><div class="scrub-label"><b id="scrubTitle">Tonight · ${timeOnly()}</b><span class="live-label"><span class="live-dot"></span>Live</span></div><input class="scrubber" id="timeScrubber" type="range" min="18" max="24" value="${Math.min(24,Math.max(18,state.cityTime.getHours()))}" step="1"><div class="scrub-times"><span>6 PM</span><span>8 PM</span><span>10 PM</span><span>12 AM</span></div><div class="map-summary"><div class="summary-item"><b style="color:var(--red)">${liveEvents||state.events.items.length}</b><small>${liveEvents?'live':'preview'} events</small></div><div class="summary-item"><b style="color:var(--orange)">${state.mbta.loading?'—':state.mbta.alerts.length}</b><small>alerts</small></div><div class="summary-item"><b style="color:var(--blue)">${state.bikes.loading?'—':(state.bikes.total||0).toLocaleString()}</b><small>bikes</small></div><div class="summary-item"><b style="color:var(--green)">${cityPulseScore()}</b><small>pulse</small></div></div></div></div>`; }

function renderSaved(){ const events=[...state.saved.values()]; return `<header class="header"><div><h1 style="font-size:31px">SAVED</h1><div class="subhead">Your Boston shortlist.</div></div></header><div class="section"><div class="section-head"><div class="section-title">Events</div><span class="pill green">${events.length} saved</span></div><div class="card">${events.length?events.map(e=>eventRow(e,true)).join(''):`<div class="empty"><div class="big">♡</div><b>Nothing saved yet</b><p style="margin-top:6px">Save things from Discover and they’ll stay here even when the live feed refreshes.</p></div>`}</div></div>${events.length>=2?`<div class="section"><div class="section-head"><div class="section-title">Tonight route</div><button class="text-btn" data-optimize>Optimize</button></div><div class="card card-pad"><div style="display:flex;align-items:center;gap:12px"><div class="logo-mark">C</div><div><b>${events.length} stops · Boston</b><div class="subhead">Saved in chronological order</div></div></div><div class="itinerary">${events.slice().sort((a,b)=>(new Date(a.start||0))-(new Date(b.start||0))).map((e,i)=>`<div class="itinerary-row"><span class="itinerary-dot">${i+1}</span><div><b>${esc(e.title)}</b><small>${esc(e.time||formatEventTime(e.start))} · ${esc(e.neighborhood||'Boston')}</small></div></div>`).join('')}</div></div></div>`:''}`; }

function sourceState(label,ok,extra=''){ return `<div class="source-row"><div class="source-icon">${label.icon}</div><div class="source-copy"><b>${esc(label.name)}</b><p>${esc(label.desc)}${extra?` · ${esc(extra)}`:''}</p></div><span class="source-state ${ok?'live':'demo'}">${ok?'live':'fallback'}</span></div>`; }
function renderMore(){ const liveEventCount=state.events.items.filter(e=>!e.preview).length; return `<header class="header"><div><div class="mini-logo"><div class="logo-mark">C</div><div><h2>CityLab V2</h2><div class="subhead">Boston intelligence console</div></div></div></div></header>
  <div class="section"><div class="section-head"><div class="section-title">Live data</div><button class="text-btn" data-refresh>Refresh</button></div><div class="data-grid"><div class="card data-card"><div class="kicker">MBTA alerts</div><strong style="color:var(--orange)">${state.mbta.loading?'—':state.mbta.alerts.length}</strong><small>${state.mbta.error?'Fallback mode':'Live V3 API'}</small></div><div class="card data-card"><div class="kicker">Bluebikes</div><strong style="color:var(--blue)">${state.bikes.loading?'—':(state.bikes.total||0).toLocaleString()}</strong><small>${state.bikes.error?'Fallback mode':'available right now'}</small></div><div class="card data-card"><div class="kicker">Live events</div><strong style="color:var(--green)">${liveEventCount||'—'}</strong><small>${state.events.source==='Ticketmaster'?'Ticketmaster sync':'add API key below'}</small></div><div class="card data-card"><div class="kicker">311 today</div><strong style="color:var(--purple)">${state.city311.today==null?'—':state.city311.today.toLocaleString()}</strong><small>${state.city311.error?'source unavailable':'Analyze Boston'}</small></div></div></div>
  <div class="section"><div class="section-head"><div class="section-title">Event integration</div></div><div class="card settings-card"><label for="tmKey">Ticketmaster Discovery API key</label><div class="key-row"><input id="tmKey" type="password" value="${esc(state.ticketmasterKey)}" placeholder="Paste API key"><button class="primary-btn" data-save-key>${state.ticketmasterKey?'Update':'Connect'}</button></div><p>The key stays in this browser's local storage. When connected, Discover swaps from preview events to live Boston listings.</p>${state.ticketmasterKey?'<button class="danger-link" data-clear-key>Remove key</button>':''}</div></div>
  <div class="section"><div class="section-head"><div class="section-title">Sources</div></div><div class="card">${sourceState({icon:'T',name:'MBTA V3',desc:'Service alerts + arrival predictions'},!state.mbta.error,state.mbta.arrivalsMode)}${sourceState({icon:'♧',name:'Bluebikes GBFS',desc:'Live station and bike availability'},!state.bikes.error)}${sourceState({icon:'✦',name:'Event layer',desc:state.events.source==='Ticketmaster'?'Ticketmaster Discovery API':'Preview catalog'},state.events.source==='Ticketmaster',state.events.lastUpdated?`updated ${state.events.lastUpdated}`:'')}${sourceState({icon:'☏',name:'Analyze Boston',desc:'BOS:311 open-data probe'},state.city311.today!=null)}</div></div>
  <div class="section"><div class="section-head"><div class="section-title">V2 changes</div></div><div class="card about-card"><p><b>Discover:</b> search, date, price, live Ticketmaster support, richer event detail sheets, persistent saved event data.</p><p><b>Transit:</b> upcoming MBTA predictions plus optional nearby-stop lookup using your location.</p><p><b>City data:</b> Bluebikes, 311 hooks, better source health, and live-vs-preview labels throughout the app.</p></div></div>`; }

function renderEventSheet(){ const e=state.activeEvent; if(!e)return ''; return `<div class="sheet-backdrop" data-close-sheet></div><section class="event-sheet" role="dialog" aria-modal="true"><div class="sheet-handle"></div><button class="sheet-close" data-close-sheet>×</button><div class="sheet-hero" style="background:${e.image?`linear-gradient(180deg,transparent,rgba(5,9,13,.85)),url('${esc(e.image)}') center/cover`:thumbGradient(e.tone)}"><div><span class="pill ${e.tone||'blue'}">${esc(e.category||'Event')}</span><h2>${esc(e.title)}</h2></div></div><div class="sheet-body"><div class="detail-line"><span>◷</span><div><b>${esc(eventDateLabel(e))}</b><small>${esc(e.time||formatEventTime(e.start))}</small></div></div><div class="detail-line"><span>⌖</span><div><b>${esc(e.venue||'Boston')}</b><small>${esc(e.neighborhood||'Boston')}</small></div></div><div class="detail-line"><span>＄</span><div><b>${esc(e.price||'See listing')}</b><small>${esc(e.source||'CityLab')}</small></div></div>${e.info?`<p class="event-description">${esc(e.info)}</p>`:''}<div class="sheet-actions"><button class="secondary-btn ${state.saved.has(e.id)?'saved':''}" data-save="${esc(e.id)}">${state.saved.has(e.id)?'♥ Saved':'♡ Save'}</button>${e.url?`<a class="primary-btn link-btn" href="${esc(e.url)}" target="_blank" rel="noopener">Open listing ↗</a>`:''}</div>${e.preview?'<div class="preview-note">This is a preview card, not a live event listing. Connect an event source in More for current listings.</div>':''}</div></section>`; }

function render(){ state.cityTime=new Date(); const screen=$('#screen'); screen.innerHTML=state.tab==='now'?renderNow():state.tab==='discover'?renderDiscover():state.tab==='live'?renderLive():state.tab==='saved'?renderSaved():renderMore(); $('#eventSheetHost').innerHTML=renderEventSheet(); $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab)); bindScreen(); }
function bindScreen(){
  $$('[data-tab-jump]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tabJump;render();scrollTo(0,0)});
  $$('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;render();});
  $$('[data-save]').forEach(b=>b.onclick=ev=>{ev.stopPropagation();saveEvent(b.dataset.save)});
  $$('[data-open-event]').forEach(b=>b.onclick=ev=>{ if(ev.target.closest('[data-save]'))return; state.activeEvent=findEvent(b.dataset.openEvent); render(); });
  $$('[data-close-sheet]').forEach(b=>b.onclick=()=>{state.activeEvent=null;render();});
  $$('[data-refresh]').forEach(b=>b.onclick=()=>refreshLive(true));
  $$('[data-layer]').forEach(b=>b.onclick=()=>{const k=b.dataset.layer;state.layers[k]=!state.layers[k];render();});
  const scrub=$('#timeScrubber'); if(scrub)scrub.oninput=()=>{const v=Number(scrub.value);$('#scrubTitle').textContent=`Tonight · ${v===24?'12 AM':(v>12?v-12:v)}:00 ${v===24?'AM':'PM'}`;};
  const loc=$('[data-location]'); if(loc)loc.onclick=()=>locateUser(true);
  const nearby=$('[data-nearby-transit]'); if(nearby)nearby.onclick=()=>locateUser(false,true);
  $$('[data-refresh-arrivals]').forEach(b=>b.onclick=async()=>{await loadHubArrivals();render();showToast('Arrivals refreshed');});
  const search=$('#eventSearch'); if(search) search.oninput=()=>{state.query=search.value; clearTimeout(search._t); search._t=setTimeout(()=>render(),180);};
  const when=$('[data-when]'); if(when)when.onchange=()=>{state.when=when.value;render();};
  const price=$('[data-price]'); if(price)price.onchange=()=>{state.price=price.value;render();};
  $$('[data-search-preset]').forEach(b=>b.onclick=()=>{state.query=b.dataset.searchPreset;render();});
  const source=$('[data-event-source]'); if(source)source.onclick=()=>{state.tab='more';render();scrollTo(0,0);};
  const saveKey=$('[data-save-key]'); if(saveKey)saveKey.onclick=async()=>{const key=($('#tmKey')?.value||'').trim(); if(!key){showToast('Paste an API key first');return;} state.ticketmasterKey=key;localStorage.setItem('citylab.ticketmasterKey',key);await loadTicketmasterEvents();render();showToast(state.events.source==='Ticketmaster'?'Live events connected':'Could not connect');};
  const clear=$('[data-clear-key]'); if(clear)clear.onclick=()=>{localStorage.removeItem('citylab.ticketmasterKey');state.ticketmasterKey='';state.events={loading:false,items:[...FALLBACK_EVENTS],source:'Preview',error:null,lastUpdated:null};render();showToast('Event key removed');};
  const optimize=$('[data-optimize]'); if(optimize)optimize.onclick=()=>showToast('Route optimization is queued for V3');
}

async function fetchJson(url,timeout=8500){ const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{signal:ctl.signal,headers:{'Accept':'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(t);} }
async function loadMbta(){ state.mbta.loading=true; try{const json=await fetchJson('https://api-v3.mbta.com/alerts?filter[route]=Green-B,Green-C,Green-D,Green-E,Orange,Red,Blue');state.mbta.alerts=json.data||[];state.mbta.error=null;}catch(e){state.mbta.alerts=[];state.mbta.error=e.message;}finally{state.mbta.loading=false;} }
function routeMeta(routeId=''){ if(routeId.startsWith('Green'))return {name:'Green Line',badge:'T',cls:'route-green'}; if(routeId==='Orange')return {name:'Orange Line',badge:'T',cls:'route-orange'}; if(routeId==='Red')return {name:'Red Line',badge:'T',cls:'route-red'}; if(routeId==='Blue')return {name:'Blue Line',badge:'T',cls:'route-blue'}; if(routeId.startsWith('SL'))return {name:'Silver Line',badge:'SL',cls:'route-silver'}; return {name:routeId||'Transit',badge:'T',cls:'route-green'}; }
function relativeArrival(iso){ if(!iso)return '—'; const mins=Math.round((new Date(iso)-new Date())/60000); if(mins<=0&&mins>-3)return 'Now'; if(mins<0)return 'Passed'; return `${mins} min`; }
async function loadPredictionsForStops(stopIds,mode){ if(!stopIds.length)return; try{const url=`https://api-v3.mbta.com/predictions?filter[stop]=${encodeURIComponent(stopIds.join(','))}&include=route,stop&sort=departure_time&page[limit]=30`; const json=await fetchJson(url); const included=json.included||[]; const stopNames=new Map(included.filter(x=>x.type==='stop').map(x=>[x.id,x.attributes?.name||x.id])); const routeNames=new Map(included.filter(x=>x.type==='route').map(x=>[x.id,x.attributes?.long_name||x.attributes?.short_name||x.id])); state.mbta.arrivals=(json.data||[]).map(p=>{const a=p.attributes||{}; const rid=p.relationships?.route?.data?.id||''; const meta=routeMeta(rid); const when=a.departure_time||a.arrival_time; return {routeId:rid,routeName:routeNames.get(rid)||meta.name,badge:meta.badge,routeClass:meta.cls,stopName:stopNames.get(p.relationships?.stop?.data?.id)||'Station',direction:a.direction_id===0?'Outbound':a.direction_id===1?'Inbound':'',when:relativeArrival(when),iso:when};}).filter(x=>x.when!=='Passed').slice(0,12); state.mbta.arrivalsError=null;state.mbta.arrivalsMode=mode;}catch(e){state.mbta.arrivalsError=e.message;} }
async function loadHubArrivals(){ await loadPredictionsForStops(['place-dwnxg','place-pktrm','place-sstat','place-kencl'],'Downtown · Park St · South Station · Kenmore'); }
async function loadNearbyArrivals(lat,lon){ try{const json=await fetchJson(`https://api-v3.mbta.com/stops?filter[latitude]=${encodeURIComponent(lat)}&filter[longitude]=${encodeURIComponent(lon)}&filter[radius]=0.012&page[limit]=12`); const ids=(json.data||[]).map(s=>s.id).filter(Boolean).slice(0,8); if(!ids.length)throw new Error('No nearby stops'); await loadPredictionsForStops(ids,'Stops near you');}catch(e){state.mbta.arrivalsError=e.message;state.mbta.arrivalsMode='Nearby lookup unavailable';} }
async function loadBikes(){ state.bikes.loading=true; try{let status,info; [status,info]=await Promise.all([fetchJson('https://gbfs.lyft.com/gbfs/1.1/bos/en/station_status.json'),fetchJson('https://gbfs.lyft.com/gbfs/1.1/bos/en/station_information.json')]);
  const statuses=status.data?.stations||[];const infos=info.data?.stations||[];const byId=new Map(statuses.map(s=>[s.station_id,s]));state.bikes.total=statuses.reduce((a,s)=>a+Number(s.num_bikes_available||0),0);state.bikes.stations=infos.map(i=>({...i,...byId.get(i.station_id)})).filter(s=>s.lat&&s.lon&&Number(s.num_bikes_available||0)>0).sort((a,b)=>Number(b.num_bikes_available||0)-Number(a.num_bikes_available||0));state.bikes.error=null;}catch(e){state.bikes.total=1340;state.bikes.stations=[];state.bikes.error=e.message;}finally{state.bikes.loading=false;} }

function tmEventToCityLab(e){ const venue=e._embedded?.venues?.[0]||{}; const c=e.classifications?.[0]||{}; const category=normalizeCategory(c.segment?.name,c.genre?.name,c.subGenre?.name); const [tone,icon]=categoryTone(category); const priceRange=e.priceRanges?.[0]; const min=priceRange?.min; const price=min==null?'See price':min===0?'FREE':`$${Math.round(min)}+`; const lat=Number(venue.location?.latitude),lon=Number(venue.location?.longitude); const p=Number.isFinite(lat)&&Number.isFinite(lon)?posFromLatLon(lat,lon):{}; const images=(e.images||[]).slice().sort((a,b)=>(b.width||0)-(a.width||0)); const image=images.find(i=>i.ratio==='16_9')?.url||images[0]?.url||''; return {id:`tm-${e.id}`,title:e.name||'Boston event',venue:venue.name||'Boston',neighborhood:venue.city?.name||'Boston',start:e.dates?.start?.dateTime||e.dates?.start?.localDate||null,time:e.dates?.start?.dateTime?formatEventTime(e.dates.start.dateTime):(e.dates?.start?.localTime||'Time TBA'),price,category,icon,tone,x:p.x,y:p.y,source:'Ticketmaster',preview:false,image,url:e.url||'',info:e.info||e.pleaseNote||''}; }
async function loadTicketmasterEvents(){ if(!state.ticketmasterKey)return; state.events.loading=true;state.events.error=null; try{const now=new Date();const end=new Date(now);end.setDate(end.getDate()+14);const params=new URLSearchParams({apikey:state.ticketmasterKey,city:'Boston',stateCode:'MA',countryCode:'US',startDateTime:now.toISOString().replace('.000',''),endDateTime:end.toISOString().replace('.000',''),size:'80',sort:'date,asc',locale:'*'}); const json=await fetchJson(`https://app.ticketmaster.com/discovery/v2/events.json?${params.toString()}`,12000); const items=(json._embedded?.events||[]).map(tmEventToCityLab); if(!items.length)throw new Error('No Boston events returned'); state.events.items=items;state.events.source='Ticketmaster';state.events.error=null;state.events.lastUpdated=new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date());}catch(e){state.events.error=`Event sync failed: ${e.message}`;state.events.source='Preview';state.events.items=[...FALLBACK_EVENTS];}finally{state.events.loading=false;} }

function pick311Resource(pkg){ const resources=pkg.result?.resources||[]; return resources.find(r=>r.datastore_active&&/new system/i.test(r.name||''))||resources.find(r=>r.datastore_active&&/2026/i.test(r.name||''))||resources.find(r=>r.datastore_active)||null; }
async function load311(){ state.city311.loading=true; try{const pkg=await fetchJson('https://data.boston.gov/api/3/action/package_show?id=311-service-requests',10000);const r=pick311Resource(pkg);if(!r)throw new Error('No live datastore resource');state.city311.resource=r.id;const sample=await fetchJson(`https://data.boston.gov/api/3/action/datastore_search?resource_id=${encodeURIComponent(r.id)}&limit=1`,10000);const rec=sample.result?.records?.[0]||{};const key=['open_dt','created_date','created_dt','createddate','open_date'].find(k=>Object.prototype.hasOwnProperty.call(rec,k));if(!key)throw new Error('Date field changed');const today=new Date();today.setHours(0,0,0,0);const yyyy=today.toISOString().slice(0,10);const sql=`SELECT COUNT(*) AS count FROM "${r.id}" WHERE "${key}" >= '${yyyy}'`;const result=await fetchJson(`https://data.boston.gov/api/3/action/datastore_search_sql?sql=${encodeURIComponent(sql)}`,10000);const val=result.result?.records?.[0]?.count;state.city311.today=val==null?null:Number(val);state.city311.error=null;}catch(e){state.city311.today=null;state.city311.error=e.message;}finally{state.city311.loading=false;} }

async function refreshLive(toast=false){ await Promise.all([loadMbta(),loadBikes(),loadHubArrivals(),load311(),state.ticketmasterKey?loadTicketmasterEvents():Promise.resolve()]);render();if(toast)showToast(state.mbta.error&&state.bikes.error?'Some live feeds unavailable':'City data refreshed'); }
function locateUser(addMarker=false,forTransit=false){ if(!navigator.geolocation){showToast('Location not available');return;}navigator.geolocation.getCurrentPosition(async pos=>{const {latitude,longitude}=pos.coords;if(forTransit){showToast('Finding nearby transit…');await loadNearbyArrivals(latitude,longitude);render();return;} if(addMarker){const p=posFromLatLon(latitude,longitude);const shell=$('.map-shell');if(shell){const m=document.createElement('div');m.className='map-marker user-marker';m.style.cssText=`left:${p.x}%;top:${p.y}%`;m.textContent='●';shell.appendChild(m);showToast('Location added to map');}}},()=>showToast('Location permission denied'),{enableHighAccuracy:false,timeout:6000,maximumAge:60000}); }

$$('.nav-item').forEach(btn=>btn.onclick=()=>{state.tab=btn.dataset.tab;state.activeEvent=null;render();scrollTo(0,0)});
render();
refreshLive(false);
setInterval(()=>{if(state.tab==='now'&&!state.activeEvent)render();},60000);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
